openapi: 3.0.0
info:
  title: NodeJS Project
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:3000/
    description: local server
  - url: http://producation.app/api
    description: production server
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
              example:
                username: nina
                password: nina
      responses:
        '201':
          description: Created

  /band-members:
    get:
      tags:
        - Band Members
      security:
        - bearerAuth: []  
      responses:
        '200': 
          description: Returns a list of band members.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id: 
                      type: string
                    name: 
                      type: string
                    instrument: 
                      type: string
                    orbitLength: 
                      type: number
                    color: 
                      type: string
                    biography: 
                      type: string
                    image:
                        type: array
                        items:
                          type: object
                          properties:
                            imageUrl: 
                              type: string
                            memberId:
                              type: string
                  example:
                    _id: 62b86377ad93686e784f8ea2
                    name: ნინა
                    instrument: პიანინო
                    orbitLength: 42
                    color: '#453454'
                    biography: მე ვარ ნინა
                    image:
                      - _id: 62a45674dcc55a6203b922b8
                        imageUrl: 'images/new-image.png'
                        memberId: 62a45674dcc55a6203b9922b9

                  
                    
  /band-member/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Band Member ID
      tags:
        - Band Members
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns band member's detailed information.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  bandMember:
                    type: object
                    properties:
                      name: 
                        type: string
                      instrument: 
                        type: string
                      orbitLength: 
                        type: number
                      color: 
                        type: string
                      biography: 
                        type: string
                      image:
                        type: array
                        items:
                          type: object
                          properties:
                            imageUrl: 
                              type: string
                            memberId:
                              type: string
              example:
                bandMember:
                    _id: 62b86377ad93686e784f8ea2
                    name: ნინა
                    instrument: პიანინო
                    orbitLength: 42
                    color: '#453454'
                    biography: მე ვარ ნინა
                    image:
                      - _id: 62a45674dcc55a6203b922b8
                        imageUrl: 'images/new-image.png'
                        memberId: 62a45674dcc55a6203b9922b9
                    

  /new-member:
    post:
      tags:
        - Band Members
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitLength:
                  type: string
                color:
                  type: string
                biography:
                  type: string
              required:
                - name
                - instrument
                - orbitLength
                - color
                - biography
              example:
                name: ნინა
                instrument: პიანინო
                orbitLength: 42
                color: '#453454'
                biography: მე ვარ ნინა
                image: []
      responses:
        '201':
          description: Created

  
  /edit-member/{id}:
     patch:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: The band member ID
      tags:
        - Band Members
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitLength:
                  type: string
                color:
                  type: string
                biography:
                  type: string
                image:
                  type: array
              required:
                - name
                - instrument
                - orbitLength
                - color
                - biography
              example:
                name: nina
                instrument: kkk
                orbitLength: 42
                color: '#453454'
                biography: biography
                image: []
      responses:
        '200':
          description: updated
  
  /delete-member/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: The band member ID
      tags:
        - Band Members
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Deleted

  /change-avatar:
    post:
      summary: Upload avatar
      tags:
        - Image Uploads
      requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    memberId:
                      type: string
                    image:
                      type: string
                      format: binary
                example:
                  memberId: 62c1c35b55e82e76bf519b1d
                  image: filename
                 
      responses:
        '200':
          description: Updated


  /change-social-icon:
    post:
      summary: Upload Social Icon
      tags:
        - Image Uploads
      requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    socialId:
                      type: string
                    image:
                      type: string
                      format: binary
                  example:
                    socialId: 62c536af82fa198e6148758c
                    image: filename
      responses:
        '200':
          description: Updated
 
  /change-band-logo:
    post:
      summary: Upload Band Logo
      tags:
        - Image Uploads
      requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    bandId:
                      type: string
                    image:
                      type: string
                      format: binary
                  example:
                    bandId: 62b88c20f75abbb01ab2f5b5
                    image: filename
      responses:
        '200':
          description: Updated

  /social-media:
    get:
      tags:
        - Social Media
      security:
        - bearerAuth: []  
      responses:
        '200': 
          description: Returns a list of social media.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    name: 
                      type: string
                    url: 
                      type: string
                  example:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
                   

                  
                    
  /social-media/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Social Media id
      tags:
        - Social Media
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns social media's detailed information.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  socialLink:
                    type: object
                    properties:
                      name: 
                        type: string
                      url: 
                        type: string
              example:
                socialLink:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
                    

  /add-social:
    post:
      tags:
        - Social Media
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
              required:
                - name
                - url
              example:
                socialLink:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
      responses:
        '201':
          description: Created

  
  /edit-social/{id}:
     patch:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: The social media ID
      tags:
        - Social Media
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
              required:
                - name
                - url
              example:
                socialLink:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
      responses:
        '200':
          description: updated
  
  /delete-social/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
            description: The social media ID
      tags:
        - Social Media
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Deleted

  /bands:
    get:
      tags:
        - About Band
      security:
        - bearerAuth: []  
      responses:
        '200': 
          description: Returns a band.
          content:
            application/json:
              schema: 
                  type: object
                  properties:
                    _id: 
                      type: string
                    about: 
                      type: string
                    image: 
                      type: array
                      items:
                          type: object
                          properties:
                            imageUrl: 
                              type: string
                            bandId:
                              type: string     
                  example:
                    _id: 62b88c20f75abbb01ab2f5b5
                    about: ბენდის შესახებ
                    image:
                      - _id: 62a45674dcc55a6203b922b8
                        imageUrl: 'images/new-image.png'
                        bandId: 62a45674dcc55a6203b9922b9

  /about-band/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Band id
      tags:
        - About Band
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns band's detailed information.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  socialLink:
                    type: object
                    properties:
                      about: 
                        type: string
              example:
                band:
                    _id: 62b88c20f75abbb01ab2f5b5
                    about: this is a good band
